--drops tables if they exist

DROP TABLE IF EXISTS LineItem;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS Author;


DROP TABLE IF EXISTS Phone;
DROP TABLE IF EXISTS Email;
DROP TABLE IF EXISTS Address;

DROP TABLE IF EXISTS Invoice;
DROP TABLE IF EXISTS User;